import { Product, Store } from './types';

export const stores: Store[] = [
  {
    id: 'hm',
    name: 'H&M',
    country: 'Sweden',
    currency: 'SEK',
  },
  {
    id: 'zara',
    name: 'Zara',
    country: 'Spain',
    currency: 'EUR',
  },
  {
    id: 'nykaa',
    name: 'Nykaa',
    country: 'India',
    currency: 'INR',
  },
  {
    id: 'kicks',
    name: 'Kicks',
    country: 'Sweden',
    currency: 'SEK',
  },
  {
    id: 'ellos',
    name: 'Ellos',
    country: 'Sweden',
    currency: 'SEK',
  },
];

// Price history for past 30 days
const generatePriceHistory = (currentPrice: number, productId: string) => {
  const history = [];
  const variation = currentPrice * 0.15;
  
  for (let i = 29; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const randomVariation = (Math.random() - 0.5) * 2 * variation;
    
    history.push({
      date: date.toISOString().split('T')[0],
      price: Math.round((currentPrice + randomVariation) * 100) / 100,
      store: stores[Math.floor(Math.random() * stores.length)].id,
    });
  }
  
  return history;
};

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Cotton T-Shirt',
    brand: 'Everyday Essentials',
    category: 'Fashion',
    image: '/api/placeholder/300/300?text=Cotton+T-Shirt',
    description: 'Premium quality cotton t-shirt perfect for everyday wear. Available in 10 colors.',
    rating: 4.7,
    reviewCount: 324,
    prices: {
      hm: 199,
      zara: 220,
      nykaa: 299,
      kicks: 189,
      ellos: 199,
    },
    priceHistory: generatePriceHistory(199, '1'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: false,
      kicks: true,
      ellos: true,
    },
    lowestPrice: 189,
    highestPrice: 299,
    averagePrice: 221,
    savingsPercent: 15,
    trending: true,
    trendingScore: 8.5,
  },
  {
    id: '2',
    name: 'Premium Skincare Serum',
    brand: 'Nordic Beauty Co',
    category: 'Beauty',
    image: '/api/placeholder/300/300?text=Beauty+Serum',
    description: 'Advanced anti-aging serum with natural Nordic ingredients. 30ml bottle.',
    rating: 4.9,
    reviewCount: 587,
    prices: {
      hm: 549,
      zara: 599,
      nykaa: 450,
      kicks: 529,
      ellos: 569,
    },
    priceHistory: generatePriceHistory(549, '2'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: true,
      kicks: true,
      ellos: false,
    },
    lowestPrice: 450,
    highestPrice: 599,
    averagePrice: 539,
    savingsPercent: 25,
    trending: true,
    trendingScore: 9.2,
  },
  {
    id: '3',
    name: 'Minimalist Canvas Backpack',
    brand: 'Urban Design',
    category: 'Accessories',
    image: '/api/placeholder/300/300?text=Canvas+Backpack',
    description: 'Eco-friendly canvas backpack with laptop compartment. Perfect for daily commute.',
    rating: 4.5,
    reviewCount: 156,
    prices: {
      hm: 399,
      zara: 449,
      nykaa: 379,
      kicks: 429,
      ellos: 419,
    },
    priceHistory: generatePriceHistory(399, '3'),
    inStock: {
      hm: true,
      zara: false,
      nykaa: true,
      kicks: true,
      ellos: true,
    },
    lowestPrice: 379,
    highestPrice: 449,
    averagePrice: 415,
    savingsPercent: 16,
    trending: false,
    trendingScore: 6.8,
  },
  {
    id: '4',
    name: 'Designer Denim Jeans',
    brand: 'Lund Denim',
    category: 'Fashion',
    image: '/api/placeholder/300/300?text=Designer+Jeans',
    description: 'Premium quality denim jeans with perfect fit. Available in multiple washes.',
    rating: 4.6,
    reviewCount: 412,
    prices: {
      hm: 799,
      zara: 899,
      nykaa: 749,
      kicks: 829,
      ellos: 799,
    },
    priceHistory: generatePriceHistory(799, '4'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: true,
      kicks: true,
      ellos: true,
    },
    lowestPrice: 749,
    highestPrice: 899,
    averagePrice: 815,
    savingsPercent: 17,
    trending: true,
    trendingScore: 7.9,
  },
  {
    id: '5',
    name: 'Natural Lip Tint',
    brand: 'Scandinavian Beauty',
    category: 'Beauty',
    image: '/api/placeholder/300/300?text=Lip+Tint',
    description: 'Long-lasting natural lip tint with moisturizing formula. 10 shades available.',
    rating: 4.8,
    reviewCount: 289,
    prices: {
      hm: 149,
      zara: 169,
      nykaa: 129,
      kicks: 159,
      ellos: 149,
    },
    priceHistory: generatePriceHistory(149, '5'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: true,
      kicks: false,
      ellos: true,
    },
    lowestPrice: 129,
    highestPrice: 169,
    averagePrice: 151,
    savingsPercent: 14,
    trending: true,
    trendingScore: 8.7,
  },
  {
    id: '6',
    name: 'Summer Linen Dress',
    brand: 'Copenhagen Styles',
    category: 'Fashion',
    image: '/api/placeholder/300/300?text=Linen+Dress',
    description: 'Breathable linen dress perfect for summer. Machine washable.',
    rating: 4.4,
    reviewCount: 198,
    prices: {
      hm: 499,
      zara: 549,
      nykaa: 459,
      kicks: 519,
      ellos: 489,
    },
    priceHistory: generatePriceHistory(499, '6'),
    inStock: {
      hm: false,
      zara: true,
      nykaa: true,
      kicks: true,
      ellos: true,
    },
    lowestPrice: 459,
    highestPrice: 549,
    averagePrice: 511,
    savingsPercent: 17,
    trending: false,
    trendingScore: 6.5,
  },
  {
    id: '7',
    name: 'Professional Hair Conditioner',
    brand: 'Nordic Care',
    category: 'Beauty',
    image: '/api/placeholder/300/300?text=Hair+Conditioner',
    description: 'Deep conditioning treatment for all hair types. 250ml bottle.',
    rating: 4.7,
    reviewCount: 421,
    prices: {
      hm: 249,
      zara: 279,
      nykaa: 219,
      kicks: 259,
      ellos: 249,
    },
    priceHistory: generatePriceHistory(249, '7'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: true,
      kicks: true,
      ellos: false,
    },
    lowestPrice: 219,
    highestPrice: 279,
    averagePrice: 251,
    savingsPercent: 12,
    trending: false,
    trendingScore: 7.1,
  },
  {
    id: '8',
    name: 'Smart Watch Pro',
    brand: 'Tech Nordic',
    category: 'Accessories',
    image: '/api/placeholder/300/300?text=Smart+Watch',
    description: 'Feature-rich smartwatch with health tracking. Water resistant.',
    rating: 4.6,
    reviewCount: 534,
    prices: {
      hm: 1499,
      zara: 1599,
      nykaa: 1399,
      kicks: 1499,
      ellos: 1549,
    },
    priceHistory: generatePriceHistory(1499, '8'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: true,
      kicks: false,
      ellos: true,
    },
    lowestPrice: 1399,
    highestPrice: 1599,
    averagePrice: 1509,
    savingsPercent: 7,
    trending: true,
    trendingScore: 8.3,
  },
  {
    id: '9',
    name: 'Cozy Winter Sweater',
    brand: 'Nordic Knits',
    category: 'Fashion',
    image: '/api/placeholder/300/300?text=Winter+Sweater',
    description: 'Warm and comfortable wool blend sweater. Perfect for cold weather.',
    rating: 4.8,
    reviewCount: 367,
    prices: {
      hm: 599,
      zara: 649,
      nykaa: 579,
      kicks: 619,
      ellos: 599,
    },
    priceHistory: generatePriceHistory(599, '9'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: false,
      kicks: true,
      ellos: true,
    },
    lowestPrice: 579,
    highestPrice: 649,
    averagePrice: 609,
    savingsPercent: 11,
    trending: true,
    trendingScore: 8.6,
  },
  {
    id: '10',
    name: 'Luxury Face Cream',
    brand: 'Scandinavian Luxe',
    category: 'Beauty',
    image: '/api/placeholder/300/300?text=Face+Cream',
    description: 'Premium moisturizing face cream with SPF protection. 50ml.',
    rating: 4.9,
    reviewCount: 623,
    prices: {
      hm: 699,
      zara: 749,
      nykaa: 649,
      kicks: 719,
      ellos: 699,
    },
    priceHistory: generatePriceHistory(699, '10'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: true,
      kicks: true,
      ellos: true,
    },
    lowestPrice: 649,
    highestPrice: 749,
    averagePrice: 701,
    savingsPercent: 8,
    trending: true,
    trendingScore: 9.1,
  },
  {
    id: '11',
    name: 'Classic Leather Belt',
    brand: 'Nordic Accessories',
    category: 'Accessories',
    image: '/api/placeholder/300/300?text=Leather+Belt',
    description: 'Genuine leather belt with minimalist buckle. Fits waist sizes 32-44.',
    rating: 4.5,
    reviewCount: 234,
    prices: {
      hm: 299,
      zara: 349,
      nykaa: 289,
      kicks: 319,
      ellos: 299,
    },
    priceHistory: generatePriceHistory(299, '11'),
    inStock: {
      hm: true,
      zara: false,
      nykaa: true,
      kicks: true,
      ellos: true,
    },
    lowestPrice: 289,
    highestPrice: 349,
    averagePrice: 311,
    savingsPercent: 13,
    trending: false,
    trendingScore: 6.2,
  },
  {
    id: '12',
    name: 'Athletic Running Shoes',
    brand: 'Nordic Sport',
    category: 'Fashion',
    image: '/api/placeholder/300/300?text=Running+Shoes',
    description: 'High-performance running shoes with superior comfort. Available in 15 sizes.',
    rating: 4.7,
    reviewCount: 456,
    prices: {
      hm: 899,
      zara: 949,
      nykaa: 849,
      kicks: 919,
      ellos: 899,
    },
    priceHistory: generatePriceHistory(899, '12'),
    inStock: {
      hm: true,
      zara: true,
      nykaa: true,
      kicks: true,
      ellos: false,
    },
    lowestPrice: 849,
    highestPrice: 949,
    averagePrice: 903,
    savingsPercent: 11,
    trending: true,
    trendingScore: 8.2,
  },
];
